export const navList = [
    {
        id:1,
        title:'Home',
        url:'/'
    },
    {
        id:2,
        title:'About',
        url:'/about'
    },
    {
        id:3,
        title:'Experience',
        url:'/experience'
    },
    {
        id:4,
        title:'Portfolio',
        url:'/portfolio'
    },
    {
        id:5,
        title:'Contact',
        url:'/contact'
    }
]